Repository micnncim/github-actions-lab, pull requests merged in 2020-05, with the labels that each got.

#9 add-labels action
  .github/actions/action-add-labels/README.md
  .github/actions/action-add-labels/action.yml
  .github/actions/action-add-labels/dist/index.js
  .github/actions/action-add-labels/src/Processor.ts
  .github/actions/action-add-labels/src/main.ts
  .github/actions/action-add-labels/test
  .github/workflows/add-labels.yml
Labels: enhancement, size/L

#17 Fix action-size action-add-labels
  .github/actions/action-add-labels/.github/workflows/test.yml
  .github/actions/action-add-labels/.prettierrc.json
  .github/actions/action-add-labels/README.md
  .github/actions/action-add-labels/__tests__/main.test.ts
  .github/actions/action-add-labels/dist/index.js
  .github/actions/action-add-labels/docs/assets/screenshot.png
  .github/actions/action-add-labels/package.json
  .github/actions/action-add-labels/src/Processor.ts
  .github/actions/action-add-labels/src/main.ts
  .github/actions/action-add-labels/yarn.lock
  .github/workflows/action-size.yml
Labels: bug, enhancement, size/XL

#23 Test: release-label
  testdata/pull-request-event.json
Labels: release/minor, size/S

#26 Test: action-get-latest-tag
  .github/actions/action-get-latest-tag/Dockerfile
  .github/actions/action-get-latest-tag/entrypoint.sh
  .github/workflows/get-latest-tag.yml
  a
Labels: size/M

#32 Test: Release with Pull Request
  testdata/pull-request-event.json
Labels: release/minor

#33 Test: Release with Pull Request
  testdata/pull-request-event.json
Labels: release/minor

#34 Test: Release with Pull Request
  testdata/pull-request-event.json
Labels: release/minor

#35 Test: Release with Pull Request
  testdata/pull-request-event.json
Labels: release/minor

#36 Test: release-with-pull-request major
  testdata/pull-request-event.json
Labels: release/major

#37 Test: release-with-pull-request patch update
  testdata/pull-request-event.json
Labels: release/patch

#38 test release with pr patch
  .github/workflows/release-with-pull-request.yml
  testdata/pull-request-event.json
Labels: release/patch

#40 test release with pr minor
  testdata/pull-request-event.json
Labels: release/minor

#41 Test: actions permission for forked repository
  testdata/pull-request-event.json
Labels: release/minor

#42 Test: actions permission for forked repository
  testdata/pull-request-event.json
Labels: release/minor

#51 Test: release-label
  testdata/pull-request-event.json
Labels: release/minor

#52 Test: release
  testdata/pull-request-event.json
Labels: release/minor

#54 Test: release
  testdata/pull-request-event.json
Labels: release/minor

#60 Test: action-get-merged-pull-request
  testdata/pull-request-event.json
Labels: documentation, enhancement

#61 Test: action-get-merged-pull-request
  testdata/pull-request-event.json
Labels: bug, documentation, enhancement, help wanted!

#62 Test: action-get-merged-pull-request
  testdata/pull-request-event.json
Labels: bug, documentation, enhancement, help wanted!

#63 Test: action-get-merged-pull-request
  testdata/pull-request-event.json
Labels: bug, documentation, enhancement, help wanted!

#68 Test: get-merged-pull-request-ts
  testdata/pull-request-event.json
Labels: documentation, enhancement, help wanted!

#69 Test: release-label
  testdata/pull-request-event.json
Labels: release/minor

#70 Test: release
  testdata/pull-request-event.json
Labels: release/minor

#71 Test: release
  testdata/pull-request-event.json
Labels: enhancement, release/minor, size/M

#72 Test: release
  testdata/pull-request-event.json
Labels: release/minor

#73 Test: release
  testdata/pull-request-event.json
Labels: release/minor

#74 Test: release
  testdata/pull-request-event.json
Labels: release/minor

#90 test
  test
Labels: release/minor
